---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/berinle/concourse-tutorial.git
- name: resource-app
  type: git
  source:
    uri: https://github.com/berinle/simple-go-web-app.git

- name: resource-deploy-web-app
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: job-deploy-app
  public: true
  serial: true
  plan:
  - get: resource-tutorial
  - get: resource-app
    trigger: true
  - task: web-app-tests
    file: resource-tutorial/10_job_inputs/task_run_tests-02.yml
  - put: resource-deploy-web-app
    params:
      manifest: resource-app/manifest.yml
      path: resource-app
