---
resources:
- name: resource-tutorial1
  type: git
  source:
    uri: https://github.com/berinle/concourse-tutorial.git
- name: resource-app
  type: git
  source:
    uri: https://github.com/berinle/simple-go-web-app.git

jobs:
- name: job-test-app
  public: true
  plan:
  - get: resource-tutorial1
  - get: resource-app
    trigger: true
  - task: web-app-tests
    file: resource-tutorial1/10_job_inputs/task_run_tests.yml
